### ISSUE TITLE
how to use genlibbc.lua to generate buildvm_libbc.h?

### ISSUE THREAD

**Issue by MichoChan** [fperrad/tvmjit#11]
I try a lot，but failed.
if you know, please let me know, thanks.

**Comment by fperrad** [comment]
This file comes from LuaJIT (branch v2.1 only).
I need to regenerate it when I worked on https://github.com/LuaJIT/LuaJIT/pull/267.
You must use the target `libbc` (see https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/Makefile#L606-L607).
But the process is not fully automatized, only one side of the conditional compilation `LJ_FR2` is generated.
You must build 2 `luajit`, one with `LJ_FR2`, another without `LJ_FR2`
For each, run `libbc`.
And finally, you must manually assemble the 2 versions of the array `libbc_code[]`.

**Comment by MichoChan** [comment]
Thanks so much.
I make it with your guide.
